import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const root = new URL('../', import.meta.url)

test('declares the official dsh bundle manifest shape', async () => {
  const pkg = JSON.parse(await readFile(new URL('package.json', root), 'utf8'))
  assert.equal(pkg.dsh.bundle.patch, './cordis.patch.yml')
  assert.equal(pkg.type, 'module')
  assert.equal(pkg.main, 'index.js')
  assert.equal(pkg.version, '1.1.0')
  assert.equal(pkg.exports['./client'], './client.js')
  assert.equal(pkg.exports['./config-source'], './config-source.js')
  assert.equal(pkg.exports['./doctor'], './doctor.js')
  assert.equal(pkg.exports['./path-guard'], './path-guard.js')
  assert.equal(pkg.exports['./runtime-guard'], './runtime-guard.js')
  assert.equal(pkg.exports['./tool-adapters'], './tool-adapters.js')
  assert.equal(pkg.exports['./sensitive'], './sensitive.js')
  assert.equal(pkg.exports['./package.json'], './package.json')
  assert.ok(pkg.files.includes('client.js'))
  assert.ok(pkg.files.includes('config-source.js'))
  assert.ok(pkg.files.includes('audit.js'))
  assert.ok(pkg.files.includes('policy.js'))
  assert.ok(pkg.files.includes('path-guard.js'))
  assert.ok(pkg.files.includes('doctor.js'))
  assert.ok(pkg.files.includes('runtime-guard.js'))
  assert.ok(pkg.files.includes('tool-adapters.js'))
  assert.ok(pkg.files.includes('scripts/build-release-metadata.mjs'))
  assert.ok(pkg.files.includes('scripts/verify-release.ps1'))
  assert.ok(pkg.files.includes('sensitive.js'))
  assert.match(pkg.peerDependencies['@deepseek-ai/dsh-settings'], />=0\.1\.2-alpha\.2 <0\.2\.0/)
  assert.match(pkg.peerDependencies['@deepseek-ai/dsh-tools'], />=0\.1\.2-alpha\.2 <0\.2\.0/)
  assert.equal(pkg.peerDependenciesMeta['@deepseek-ai/dsh-settings'].optional, true)
  assert.equal(pkg.dsh.client.platform, 'web')
  assert.ok(pkg.dsh.client.inject.includes('@deepseek-ai/dsh-client-ui-settings-plugins'))
  assert.ok(!pkg.dsh.client.inject.includes('@deepseek-ai/dsh-client-runtime'))
  assert.equal(pkg.scripts.prepare, undefined)
  assert.ok(pkg.keywords.includes('dsh-plugin'))
})

test('host plugin declares the settings service used by the live section', async () => {
  const source = await readFile(new URL('index.js', root), 'utf8')
  assert.match(source, /export const inject = \['tools', 'settings'\]/)
  assert.match(source, /ctx\.settings\.installSection\(ctx, SETTINGS_NAMESPACE, Config, config/)
})

test('bundle patch mounts the published package name', async () => {
  const patch = await readFile(new URL('cordis.patch.yml', root), 'utf8')
  assert.match(patch, /id:\s*windows-workspace-guard/)
  assert.match(patch, /name:\s*dsh-windows-workspace-guard/)
  assert.match(patch, /mode:\s*block/)
  assert.match(patch, /toolNames:\s*\n\s*- pwsh/)
  assert.match(patch, /- read/)
  assert.match(patch, /- read_image/)
  assert.match(patch, /- write/)
  assert.match(patch, /- edit/)
  assert.match(patch, /- glob/)
  assert.match(patch, /- grep/)
  assert.match(patch, /- str_replace_editor/)
  assert.match(patch, /guardSystem:\s*true/)
  assert.match(patch, /guardProcesses:\s*true/)
  assert.match(patch, /guardNativeEscapes:\s*true/)
  assert.match(patch, /guardPersistentShell:\s*true/)
  assert.match(patch, /guardExistingLinks:\s*true/)
  assert.match(patch, /guardSensitiveData:\s*true/)
  assert.match(patch, /sensitivePaths:\s*\[\]/)
  assert.match(patch, /requireAbsoluteMutationPaths:\s*true/)
})
